site_name: Click 中文文档 (8.4.1-zh)
site_url: https://github.io
site_author: cittyan

repository_name: cittyan/click
repo_url: https://github.com
edit_uri: edit/8.4.1-zh/docs/

theme:
  name: material
  language: zh # 设为中文界面
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到暗黑模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.tabs # 开启顶部导航标签
    - navigation.top # 开启返回顶部按钮
    - search.suggest # 开启搜索建议

docs_dir: docs # 指定您的文档目录

# 根据您的 docs/ 目录实际结构，在此处定义导航栏（示例）
nav:
  - 首页: index.md
